import Navebar from "../components/Navebar";
import Footer from "../components/Footer";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navebar / >
        {children}
        <Footer />
      </body>
    </html>
  );
}
